
service: authapiaws

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 2048
  stage: dev
  timeout: 20
  region: us-east-1

functions:
  fun:
    handler: handler.fun 
    events:
      - http: ANY /{proxy+}
      - http: ANY /